
name: Sasha Archive Cracker
on: [workflow_dispatch]
jobs:
  crack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install fcrackzip
        run: sudo apt-get update && sudo apt-get install -y fcrackzip
      - name: Brute Force and Reveal
        run: |
          echo "üïµÔ∏è‚Äç‚ôÄÔ∏è –ù–∞—á–∏–Ω–∞—é —à—Ç—É—Ä–º —Å—Ç–∞—Ä–æ–≥–æ –∞—Ä—Ö–∏–≤–∞..."
          # –ó–∞–ø—É—Å–∫–∞–µ–º –ø–µ—Ä–µ–±–æ—Ä –∏ —Å–æ—Ö—Ä–∞–Ω—è–µ–º —Ä–µ–∑—É–ª—å—Ç–∞—Ç –≤ –ø–µ—Ä–µ–º–µ–Ω–Ω—É—é
          RESULT=$(fcrackzip -v -u -l 1-8 -c '1' Vless.zip)
          
          echo "------------------------------------------"
          echo "‚ú® BOSS, –°–ú–û–¢–†–ò –°–Æ–î–ê! –ü–ê–†–û–õ–¨ –ù–ò–ñ–ï: ‚ú®"
          echo "$RESULT"
          echo "------------------------------------------"
          
          # –í—ã—Ç–∞—Å–∫–∏–≤–∞–µ–º —Å–∞–º–æ —Å–ª–æ–≤–æ/—á–∏—Å–ª–æ –ø–∞—Ä–æ–ª—è
          PW=$(echo $RESULT | awk '{print $5}')
          
          echo "üìÑ –°–û–î–ï–†–ñ–ò–ú–û–ï Vless.txt:"
          unzip -P "$PW" -p Vless.zip
