
name: Sasha Archive Cracker
on: [workflow_dispatch]
jobs:
  crack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y fcrackzip
      - name: Run Brute Force
        run: |
          if [ -f "Vless.zip" ]; then
            fcrackzip -v -u -l 1-8 -c '1' Vless.zip
          else
            echo "❌ ФАЙЛА Vless.zip НЕТ В РЕПОЗИТОРИИ!"
            exit 1
          fi
