name: "ðŸš€ STELLA TOTAL ENGINE"
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {contents: write}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install aiohttp
      - run: python engine.py
      - name: Deploy
        run: |
          git config --global user.name "Blondie-Bot"
          git config --global user.email "stella@ai.com"
          git add .
          git commit -m "ðŸ’… Stella: Total Sync" --allow-empty
          git push
