
name: Auto Update
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests
      - run: python core_sync.py
      - name: Check files and push
        run: |
          git config user.name "Blondie-Bot"
          git config user.email "bot@ai.com"
          # –ï—Å–ª–∏ —Ñ–∞–π–ª—ã –ø–æ—è–≤–∏–ª–∏—Å—å, –¥–æ–±–∞–≤–ª—è–µ–º –∏ –ø—É—à–∏–º
          if ls sub*.txt 1> /dev/null 2>&1; then
            git add sub*.txt
            git commit -m "üöÄ Auto-Update"
            git push
          else
            print "–ù–∏–∫–∞–∫–∏—Ö –∏–∑–º–µ–Ω–µ–Ω–∏–π –Ω–µ –Ω–∞–π–¥–µ–Ω–æ."
          fi
