
name: Auto Update
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - run: pip install requests google-generativeai
      - env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python core_sync.py
      - run: |
          git config --global user.name "Blondie-Pro"
          git config --global user.email "blondie@ai.com"
          git add .
          git commit -m "ðŸš€ Auto-Sync" || exit 0
          git push
        